const express = require('express')
const mongoose = require('mongoose')
const cors = require('cors')
const dotenv = require('dotenv')
dotenv.config()
const app = express()
app.use(cors())
app.use(express.json())
mongoose.connect(process.env.MONGO_URI)
    .then(() => console.log('MongoDB Connected'))
    .catch((error) => console.log(error))
const promptRoutes = require('./routes/promptRoutes')
app.use('/api/prompts', promptRoutes)
const PORT = process.env.PORT || 5000
app.listen(PORT, () => {
    console.log(`Server Running on Port ${PORT}`)
})